language: node_js
node_js:
  - "stable"
  
services:
  - docker
cache:
   directories:
     - node_modules
     
before_script:
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl
  - echo "$KUBE_CA" | base64 --decode > ca.pem
  - echo "$KUBE_CLIENT_KEY" | base64 --decode > admin-key.pem
  - echo "$KUBE_CLIENT_CERT" | base64 --decode > admin.pem

  - kubectl config set-cluster default-cluster --server="$KUBE_API" --certificate-authority=ca.pem
  - kubectl config set-credentials admin --certificate-authority=ca.pem --client-key=admin-key.pem --client-certificate=admin.pem 
  - kubectl config set-context default-system --cluster=default-cluster --user=admin
  - kubectl config use-context default-system
  - kubectl config view
  - kubectl version
  - kubectl get nodes
  - npm install
script:
  - npm test
  - docker build -t alexlokshin/crawler .
after_script:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - if [ ! -z "$TRAVIS_TAG" ]; then export IMAGE_TAG=$TRAVIS_TAG; else export IMAGE_TAG=$TRAVIS_BRANCH; fi
  - docker push "alexlokshin/crawler:$TRAVIS_TAG"
  - docker push "alexlokshin/crawler:$TRAVIS_BUILD_NUMBER"
  - docker push alexlokshin/crawler:latest
