language: node_js
node_js:
  - "stable"
before_script:
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl
  - echo "$KUBE_CA" > ca.pem
  - echo "$KUBE_CLIENT_KEY" > admin-key.pem
  - echo "$KUBE_CLIENT_CERT" > admin.pem
  - cat ca.pem

  - kubectl config set-cluster default-cluster --server="https://$KUBE_API" --certificate-authority=ca.pem
  - kubectl config set-credentials admin --certificate-authority=ca.pem --client-key=admin-key.pem --client-certificate=admin.pem 
  - kubectl config set-context default-system --cluster=default-cluster --user=admin
  - kubectl config use-context default-system
  - kubectl config view
  - kubectl version
  - kubectl get nodes
