apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: crawler-ingress
  namespace: services
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /crawler
        backend:
          serviceName: crawler-service
          servicePort: 80
