apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: crawler-ingress
  namespace: services
spec:
  rules:
  - http:
      paths:
      - path: /crawler
        backend:
          serviceName: crawler-service
          servicePort: 80
